ss

diff --git a/pwnd-update b/pwnd-update
--- a/pwnd-update
+++ b/pwnd-update
@@ -1,7 +1,10 @@
 #!/bin/bash
 if [ $EUID -ne 0 ]; then
-	echo "Error: run $0 with root"
-	exit 1
+	su
+	if[ $? -ne 0 ]; then
+		echo "Error: must be run with root"
+		exit 1
+	fi
 fi
 killall -s 9 pwn
 service pwnd stop
